version: '3.9'
services:
  node-app:
    build: .
    container_name: node-api
    environment:
      - PORT=8000
      - NODE_ENV=development
    command: ["node", "index.js"]
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    container_name: node-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hello123
    volumes:
      - mongo-db:/data/db

  nginx:
    image: nginx:1.21.5-alpine
    container_name: store-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
   
volumes:
  mongo-db: