version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8000:8000"
    container_name: node-api
    environment:
      - PORT=8000
      - NODE_ENV=production
    command: ["node", "index.js"]
    